### ISSUE TITLE
Headings H3 - H6 are assigned incorrect textmate scopes

### ISSUE THREAD

**Issue by icorbrey** [wooorm/markdown-tm-language#11]
Since H1 is assigned `markup.heading.atx.1` and H2 is assigned `markup.heading.atx.2`, H3 - H6 should be assigned `markup.heading.atx.3`, `markup.heading.atx.4`, and so on. Instead, H3 - H6 are all assigned `markup.heading.atx.2`. This is affecting downstream packages like the MDX extension for VSCode (see: https://github.com/mdx-js/mdx-analyzer/issues/483).

**Comment by icorbrey** [comment]
For reference, the downstream issue: https://github.com/mdx-js/mdx-analyzer/issues/483

**Comment by wooorm** [comment]
https://github.com/mdx-js/mdx-analyzer/issues/483#issuecomment-2467868352 Feel free to pick where to discuss this. But I responded there.
