### ISSUE TITLE
Strikethrough doesn’t work in VSCode

### ISSUE THREAD

**Issue by remcohaszing** [wooorm/markdown-tm-language#2]
Strikethrough syntax (`~~text~~`) isn’t highlighted in VSCode. I see it is being highlighted on https://wooorm.com/markdown-tm-language, but it uses the same colors as a syntax error.

**Comment by wooorm** [comment]
Please add which theme you are using

**Comment by remcohaszing** [comment]
I use _[blackai-theme](https://marketplace.visualstudio.com/items?itemName=asilverio.blackai-visual-studio-code)_, but also reproduced it using a temporary VSCode profile, which uses _Dark+ (Default dark)_. Inspecting using the web inspector shows no element is created for the strikethrough tokens.

**Comment by wooorm** [comment]
Default dark is very minimal, it doesn’t show many things.
That being said, solarized is the same!

**Comment by remcohaszing** [comment]
I thought they would have different HTML elements with different class names though, although styled the same. Is this not the case then?

I suppose this question is more related to how Monaco / VSCode handles this internally than to the language.

**Comment by wooorm** [comment]
Themes have selectors. They match the names provided here. Sort of like CSS but different.
If the selectors don’t match, nothing happens: no element.
If they do match, only some foreground/background/font-style stuff is passed through.

Example: https://github.com/sdras/night-owl-vscode-theme/blob/f260cea5356261337d18809bdbe922952c7a6fa4/themes/Night%20Owl-color-theme-noitalic.json#L1402-L1409

And then VS Code grammars/themes use different names than GH/Atom does.

And then there’s hundreds of languages and hundreds of themes. So it’s messy
