### ISSUE TITLE
Indented code blocks cause text to be marked as invalid.

### ISSUE THREAD

**Issue by MarkvanMents** [wooorm/markdown-tm-language#6]
## Describe the bug
If I am viewing changes from commits for a markdown file, large amounts of text are marked invalid at the end of an indented code block. I believe the markdown is valid (the file is displayed correctly in a number of markdown editors) and the highlighting makes the code very difficult to read.

I have only noticed this happening for the last few months.

See example images below.
![277599992-fa6e9152-5e25-4eba-8ca7-85189c3cc724](https://github.com/wooorm/markdown-tm-language/assets/35492184/786983c6-ee7e-4730-a591-e65d8af7afa7)

This is rendered (in GitHub) as

![277600337-1be03f3e-af25-4458-af12-f24dc7621924](https://github.com/wooorm/markdown-tm-language/assets/35492184/1311202a-b22c-415d-9995-0a1a439fe7cf)

which is what I wanted. So I can't see where the error is.

Here's a link to an example in my public repo. https://github.com/mendix/docs/commit/20b334e90d4f069326b4a1e4a51120801b900660#diff-fa4e89b8b6b7fca9589f44b77d58a53d33c15272a2853b46e55e86e0aee2e7f0R205

### Expected behaviour
There should be no highlighting for this syntax. If the indented code block ticks are a syntax error according to strict Markdown, then only the ticks should be highlighted. But I don't believe this should be highlighted at all.

### Additional notes
I've raised this with github-linguist (https://github.com/github-linguist/linguist/issues/6587), but I have been redirected here to report the problem.

**Comment by wooorm** [comment]
Hey! That’s a bug. Thanks!

Your markup is a bit messy. You get the red stuff inside the JSON too, because you use unquoted strings.

On the markdown side, your indentation is **valid** but quite wild. You use four spaces as indentation but not for the first paragraph. And that indent of the first paragraph is what is used.
If you clean it up, it looks more like how it actually works in markdown:

messy:

```markdown
1. x
    * y
    * z
        ```json
        {}
        ```
```

classy:

```markdown
1. x
   * y
   * z
     ```json
     {}
     ```
```

also classy:

```markdown
1.  x
    *   y
    *   z
        ```json
        {}
        ```
```

---

As for the bug you found, here’s it smaller:

````markdown
~~~markdown
*   ```json
    {}
    ```
~~~
````

~~~markdown
*   ```json
    {}
    ```
~~~

Removing one more space solves it. So it somehow has to do with the four spaces breaking it.

**Comment by MarkvanMents** [comment]
Hi Titus,
Thanks for the quick response. Sorry the example was so large 😀.
Hope you can find what the problem is as it is very useful to have real Markdown errors highlighted. Currently I'm just ignoring anything in red!

**Comment by wooorm** [comment]
> it is very useful to have real Markdown errors highlighted

markdown does not have errors, every character is valid. It sometimes doesn’t work the way you want (and that’s what you probably mean with errors), but it’ll never crash.

---

> Hope you can find what the problem

Hmm, I don’t know. This only happens with GitHub’s tooling. And that’s their internal closed source tooling that I can’t access. It works fine in VS Code.

**Comment by wooorm** [comment]
Alright, I tested with TextMate. Was able to repro. And so also managed to solve it. And it also still works in our demo with VS Code. So I think this is solved! It takes time for linguist and then GH to pull it in though!

**Comment by MarkvanMents** [comment]
Thanks for your quick and positive response. Looking forward to seeing these changes in GitHub when they get there.

**Comment by MarkvanMents** [comment]
Hi Titus,
Just to let you now that GitHub seems to have pulled in your update and everything looks great and much more readable.
Thanks very much for resolving this.
Mark
