### ISSUE TITLE
Trailing ESM doesn’t break out of nested code block

### ISSUE THREAD

**Issue by remcohaszing** [wooorm/markdown-tm-language#8]
When using an `mdx` code block, if the nested MDX has ESM on the last line, it keeps syntax highlighting even after the code block is closed. Instead, I expect the closing code block to fully terminate the embedded language.

````mdx
Before (expected): `1/2`

```mdx
import '@mdx-js/mdx'
```

After (actual): `1/2`
````

For future reference:

![screenshot of the code block above](https://github.com/wooorm/markdown-tm-language/assets/779047/cfc53a65-1229-47bd-8fc9-0fe8264210ca)

**Comment by wooorm** [comment]
The nested part is important.

> Instead, I expect the closing code block to fully terminate the embedded language.

Technically, grammars cannot do that. The embedded language has to be done / “paused”. Then a closing can be accepted. Things cannot be force closed the other way around.

**Comment by wooorm** [comment]
thanks!
