### ISSUE TITLE
Unclosed curly bracket causes syntax highlighting to stop

### ISSUE THREAD

**Issue by karlhorky** [wooorm/markdown-tm-language#9]
Highlighting of a non-paired opening curly bracket in a code block in MDX with `markdown-tm-language` (`.mdx` file via [the MDX VS Code extension](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx)) causes the highlighting to stop after the code block:

````mdx
```tsx
export default function App(props) {
  console.log('>> Console logging from Expo app');
```

![Expo dev server](expo-console-logging.avif)

<div>abc</div>
````

![Screenshot 2024-07-08 at 22 26 38](https://github.com/wooorm/markdown-tm-language/assets/1935696/746845d9-9358-4a18-9a2e-8228e5150424)

Adding the missing closing curly bracket fixes the highlighting:

![Screenshot 2024-07-08 at 22 31 50](https://github.com/wooorm/markdown-tm-language/assets/1935696/162f13c5-3019-44f9-a1ba-97aee79fd94e)

Markdown highlighting in VS Code (`.md` file, without MDX extension installed) with the unmatched opening curly bracket, for comparison:

![Screenshot 2024-07-08 at 22 26 49](https://github.com/wooorm/markdown-tm-language/assets/1935696/79cd3711-4f44-4eba-a3fe-902f379b1310)

**Comment by wooorm** [comment]
Thanks, done!

**Comment by karlhorky** [comment]
Wow super fast, thanks!
